app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, TextAreaField, FileField, SubmitField
from wtforms.validators import DataRequired

class BookForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    publication_date = StringField('Publication Date')
    description = TextAreaField('Description')
    cover_image = StringField('Cover Image')
    submit = SubmitField()

app/__init__.py
from flask import current_app, Flask
from config import Config

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    # Register Blueprints
    from .routes import bp
    app.register_blueprint(bp)

    # Test route to make sure the app is running:
    @app.route('/hello')
    def hello():
        return ('Hello, World')
    
    return app

app/routes.py
from flask import Blueprint, render_template, url_for, request, redirect, jsonify
from app.forms import BookForm
import firestore

bp = Blueprint('app', __name__)

@bp.route('/')
def index():
    start_after = request.json['start_after']
    if start_after:
        return jasonify(books)
    #books = firestore.read_all()
    books, last_title = firestore.read_limit(start_after=start_after)
    return render_template('list.html', books=books, last_title=last_title)


@bp.route('/add', methods=['GET', 'POST'])
def add():
    """Add a new book to the firestore database

    Return user to the view page for the new book"""
    form = BookForm()

    if form.validate_on_submit():
        data = form.data

        # Processs image if there is one
        # COME BACK

        book = firestore.create(data)
        return redirect(url_for('app.view', book_id=book['id']))

    return render_template('book_form.html', form=form, header="Add Book")

@bp.route('/<book_id>/update', methods=['GET', 'POST'])
def update(book_id):
    book = firestore.read(book_id)
    form = BookForm(data=book)

    # Process form if submission request
    if form.validate_on_submit():
        data = form.data
        book = firestore.update(data, book_id)
        return redirect(url_for('app.view', book_id=book['id']))
    
    book = firestore.read(book_id)
    return render_template('book_form.html', form=form, header="Update Book")

@bp.route('/<book_id>/delete', methods=['GET'])
def delete(book_id):
    firestore.delete(book_id)
    return redirect(url_for('app.index'))


@bp.route('/<book_id>')
def view(book_id):
    book = firestore.read(book_id)
    return render_template('view.html', book=book)

@bp.route('/ajax', methods=['POST'])
def ajax():
    if request.method == "POST":
        print(request.json['start_after'])

    
    return 'response to ajax request'

app/templates/base.html
<!DOCTYPE html>
    <html>
        <head>
            <!--Import Google Icon Font-->
            <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
            <!-- Compiled and minified CSS -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
            <link rel="stylesheet" href="{{ url_for('static', filename='style1.css') }}">
        
            <style>{% block style %}{% endblock %}</style>
          
            <title>{% block title %}{% endblock %}</title>
            <!--Let browser know website is optimized for mobile-->
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        </head>

        <body>
            
                {% block navbar %}{% endblock %}
                {% block content %}{% endblock %}
            
            <!--JavaScript at end of body for optimized loading-->
            <!-- Compiled and minified JavaScript -->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
            {% block scripts %}{% endblock %}
            {% block mobile %}{% endblock %}
        </body>
    </html>

app/templates/book_form.html
{% extends 'base.html' %}


{% block content %}
    {% include 'nav_bar.html' %}

    <div class="container">
    <h4>{{ header }}</h4>
    <div class="row">
        <form action="" method='post' class="col s12">
            {{ form.hidden_tag() }}

            <div class="row">
                <div class="input-field col s12">
                    {{ form.title() }}
                    {{ form.title.label }}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    {{ form.author() }}
                    {{ form.author.label }}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    {{ form.publication_date(class="datepicker") }}
                    {{ form.publication_date.label }}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    {{ form.description(class="materialize-textarea") }}
                    {{ form.description.label }}
                </div>
            </div>

            <div class="row">
                <div class="file-field input-field col s12">
                    <div class="btn">
                        <span>Cover Image</span>
                        <input type="file">
                    </div>
                    <div class="file-path-wrapper">
                        {{ form.cover_image(class="file-path validate") }}
                        
                      </div>
                    
                </div>
            </div>

            <div class="row">
                <div class="col s12">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                        <i class="material-icons right">send</i>
                      </button>
                </div>
                
            </div>
        </form>
    </div>
</div>


{% endblock %}

{% block scripts %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.datepicker');
    var instances = M.Datepicker.init(elems);
  });
</script>

  {% endblock %}

app/templates/list.html
{% extends 'base.html' %}

{% include 'nav_bar.html' %}

{% block content %}
    <div id="list-content" class="container">
        {% for book in books %}
            <div class="col s12 m8 offset-m2 l6 offset-l3">
                <div class="card-panel grey lighten-5 z-depth-1">
                    <div class="row valign-wrapper">
                        <div class="col s12 m2">
                            {% if book['cover_image'] %}
                                <a href="{{ url_for('app.view', book_id=book['id']) }}"><img src="{{ book['cover_image'] }}" alt="" class="responsive-img"></a>
                            {% else %}
                                <a href="{{ url_for('app.view', book_id=book['id']) }}"><img src="https://via.placeholder.com/150" alt="" class="responsive-img"></a>
                                
                            {% endif %}
                        </div>
                        <div class="col s12 m10">
                            <span class="black-text">
                                <h5><a href="{{ url_for('app.view', book_id=book['id']) }}">{{ book['title'] }}</a></h5>
                                <p><span class="">{{ book['publication_date'] }}</span><br>
                                {{ book['author'] }}<br>
                                {{ book['description'] }}</p>              
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if last_title %}
        <div class="pager">            
            <a href="?start_after={{ last_title }}" class="waves-effect waves-light btn">Load More</a>
        </div>
        {% endif %}

        <!-- Floating Add-->
        <div class="fixed-action-btn">
            <a href="{{ url_for('app.add') }}" class="btn-floating btn-large red">
              <i class="large material-icons">add</i>
            </a>
          </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.fixed-action-btn');
        var instances = M.FloatingActionButton.init(elems);
    });
</script>
<script>
    document.onscroll = function(){
        var lastTitle = '{{ last_title }}';
        var container = document.getElementById('list-content')
        var bottom = document.body.scrollHeight - window.innerHeight
        if (document.body.scrollTop == bottom || document.documentElement.scrollTop == bottom) {
            // Send ajax request to load more 
        
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function(){
                container.innerHTML += 
                    `<div class="col s12 m8 offset-m2 l6 offset-l3">
                        <div class="card-panel grey lighten-5 z-depth-1">
                            <div class="row valign-wrapper">
                                <div class="col s12 m2">
                                        <a href="#"><img src="https://via.placeholder.com/150" alt="" class="responsive-img"></a>
                                </div>
                                <div class="col s12 m10">
                                    <span class="black-text">
                                        <h5><a href="#">AJAX BOOK TITLE</a></h5>
                                        <p><span class="">Nov 13, 1984</span><br>
                                        Justin Bird<br>
                                        The best!</p>              
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>`;
            }
            const jsonString = JSON.stringify({start_after: lastTitle})
            xhttp.open("POST", "{{ url_for('app.ajax') }}");
            xhttp.setRequestHeader("Content-Type", "application/json")
            xhttp.send(jsonString);

  }
  } 
    
</script>
{% endblock %}

app/templates/nav_bar.html
{% block navbar %}  
  <nav>
    <div class="nav-wrapper container">
      <a href="{{ url_for('app.index') }}" class="brand-logo">Bookshelf</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="{{ url_for('app.add') }}">Add Book</a></li>
        <li><a href="{{ url_for('app.index') }}">Books</a></li>
      </ul>
      <ul id="nav-mobile" class="sidenav">
        <a href="{{ url_for('app.index') }}" class="red lighten-2">Bookshelf</a>
        <!--<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>-->
        <li><a href="{{ url_for('app.add') }}">Add Book</a></li>
        <li><a href="{{ url_for('app.index') }}">Books</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger">
        <i class="material-icons">menu</i>
      </a>
    </div>
  </nav>
{% endblock %}

{% block scripts %}
<script>
 document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.sidenav');
    var instances = M.Sidenav.init(elems);
  });

  // Initialize collapsible (uncomment the lines below if you use the dropdown variation)
  // var collapsibleElem = document.querySelector('.collapsible');
  // var collapsibleInstance = M.Collapsible.init(collapsibleElem, options);


</script>
{% endblock %}

app/templates/view.html
{% extends 'base.html' %}

{% include 'nav_bar.html' %}
{% block content %}
<div class="container">
    <h4>Book</h4>
    <div class="btn-group">
        <a href="{{ url_for('app.update', book_id=book['id']) }}" class="waves-effect waves-light btn">Edit</a>
        <a href="{{ url_for('app.delete', book_id=book['id']) }}"class="waves-effect waves-light red lighten-2 btn">Delete</a>
    </div>
    
    
    <div class="col s12 m8 offset-m2 l6 offset-l3">
        <div class="card-panel grey lighten-5 z-depth-1">
          <div class="row valign-wrapper">
            <div class="col s12 m2">
            {% if book['cover_image'] %}
                <img src="{{ book['cover_image'] }}" alt="" class="responsive-img">
            {% else %}
                <img src="https://via.placeholder.com/150" alt="" class="responsive-img">
            {% endif %}
            </div>
            <div class="col s12 m10">
              <span class="black-text">
                <h5>{{ book['title'] }}</h5>
                <p><span class="">{{ book['publication_date'] }}</span><br>
                    {{ book['author'] }}<br>
                    {{ book['description'] }}</p>              
              </span>
            </div>
          </div>
        </div>
      </div>
</div>
    


{% endblock %}